---
- name: Configure FRR for BGP
  hosts: localhost
  become: yes
  tasks:
    - name: Create FRR BGP config
      copy:
        dest: /etc/frr/frr.conf
        content: |
          frr version 8.4
          frr defaults traditional
          hostname nva
          service integrated-vtysh-config
          log syslog

          router bgp 65020
            bgp router-id 172.16.2.4
            no bgp ebgp-requires-policy
            neighbor 10.3.0.12 remote-as 65515
            neighbor 10.3.0.12 ebgp-multihop 5
            neighbor 10.3.0.12 update-source eth0
            network 8.8.8.8/32
          !
          line vty
            exec-timeout 0 0
            privilege level 15
            login

    - name: Enable and start FRR service
      service:
        name: frr
        state: started
        enabled: yes
